name: release

on:
  workflow_dispatch:
    inputs:
      npm_token:
        description: 'npm access token'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ github.event.inputs.npm_token }}
          npm publish --ignore-scripts
